// This file is auto-generated or manually updated to list all existing images in public/images/
// This ensures client-side components can verify file existence without calling Node's fs module.

export const existingImages: Record<string, boolean> = {
  "/images/logo/logo-horizontal.png": true,
  "/images/logo/logo-stacked.png": true,
  "/images/logo/logo-navy.png": true,
  "/images/logo/logo-icon.png": true,
  "/images/logo/logo.svg": true,
  "/images/logo/logo.png": true,
  "/images/logo/logo-white.svg": true,
  "/images/logo/logo-white.png": true,
  "/images/doctors/dr-sudarshan-dev-arya.jpg": true,
  "/images/doctors/dr-manisha-bangarwa-arya.jpg": true,
  "/images/clinic/exterior.jpg": true,
  "/images/clinic/reception.jpg": true,
  "/images/clinic/waiting-area.jpg": true,
  "/images/clinic/vaccination-room.jpg": true,
  "/images/clinic/consultation-room.jpg": true,
  "/images/hero/hero-1.jpg": true,
  "/images/hero/doctor-baby-both.png": true,
  "/images/gallery/gallery-1.jpg": true,
  "/images/gallery/gallery-2.jpg": true,
  "/images/gallery/gallery-3.jpg": true,
  "/images/gallery/gallery-4.jpg": true,
  "/images/gallery/gallery-5.jpg": true,
  "/images/gallery/gallery-6.jpg": true,
  "/images/gallery/gallery-7.jpg": true,
  "/images/gallery/gallery-8.jpg": true,
  "/images/illustrations/doctor-baby.webp": true,
  "/images/illustrations/family-child.webp": true,
  "/images/illustrations/growth-journey.webp": true,
  "/images/illustrations/mascot.webp": true,
  "/images/illustrations/parent-guidance-premium.webp": true,
  "/images/illustrations/growth-journey-premium.webp": true,
  "/images/illustrations/empty-state.webp": true,
};
